№1

In [2]:
import numpy as np

print("№1")
m1 = np.arange(1, 11)
print(m1)

print("№2")
m2 = np.zeros((3, 3))
print(m2)

print("№3")
m3 = np.random.randint(1, 11, (5, 5))
print(m3)

print("№4")
m4 = np.random.random((4, 4))
print(m4)

print("№5")
a5 = np.random.randint(1, 11, 5)
b5 = np.random.randint(1, 11, 5)

print(a5 + b5)
print(a5 - b5) # + - * векторів відповідно
print(a5 * b5)

print("№6")
a6 = np.random.random(7)
b6 = np.random.random(7)

print(np.dot(a6, b6)) #скалярний добуток

print("№7")

a7 = np.random.randint(1, 11, (2, 2))
b7 = np.random.randint(1, 11, (2, 3))

print(np.dot(a7, b7))

print("№8")

m8 = np.random.randint(1, 11, (3, 3))
m8_inv = np.linalg.inv(m8)
print(m8_inv)

print("№9")
m9  = np.random.random((4, 4))
m9_T = m9.T
print(m9_T)

print("№10")

m10 = np.random.randint(1, 11, (3, 4))
v10 = np.random.randint(1, 11, 4)

print(np.dot(m10, v10))

print("№11")

m11 = np.random.random((2, 3))
v11 = np.random.random(3)

print(np.dot(m11, v11))

print("№12")

a12 = np.random.randint(1, 11, (2, 2))
b12 = np.random.randint(1, 11, (2, 2))

print(a12 * b12)

print("№13")

a13 = np.random.randint(1, 11, (2, 2))
b13 = np.random.randint(1, 11, (2, 2))

print(np.dot(a13, b13))

print("№14")

m14 = np.random.randint(1, 101, (5, 5))
print(np.sum(m14))

print("№15")

a15 = np.random.randint(1, 11, (4, 4))
b15= np.random.randint(1, 11, (4, 4))

print(a15 - b15)

print("№16")

m16 = np.random.random((3, 3))
row_sums = np.sum(m16, axis=1).reshape(-1, 1)

print(row_sums)

print("№17")

m17 = np.random.randint(1, 11, (3, 4))
m_square = np.square(m17)

print(m_square)

print("№18")

v18 = np.random.randint(1, 51, 4)
v18_root = np.sqrt(v18)

print(v18)

№1
[ 1  2  3  4  5  6  7  8  9 10]
№2
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
№3
[[ 5  5  3  5  5]
 [ 5 10  3  6  6]
 [ 9  8  4  9  6]
 [ 8  7 10  1  5]
 [ 7  1  8 10 10]]
№4
[[0.7354025  0.83728089 0.66878058 0.50226889]
 [0.76263574 0.2663604  0.96496514 0.28272831]
 [0.93653544 0.17592071 0.69943748 0.04851671]
 [0.21022981 0.4062197  0.39842283 0.47232467]]
№5
[ 7 13 12 12 10]
[-3 -3  0 -6 -8]
[10 40 36 27  9]
№6
1.5669189215446035
№7
[[ 93  52  99]
 [123 108 153]]
№8
[[ 0.10509554 -0.00318471 -0.01910828]
 [-0.14968153  0.15605096 -0.06369427]
 [ 0.04936306 -0.06210191  0.12738854]]
№9
[[0.2538584  0.23904109 0.93646684 0.62115664]
 [0.64485815 0.65027645 0.33304554 0.57819774]
 [0.46887646 0.6087238  0.96084967 0.9764794 ]
 [0.23817554 0.27915814 0.06198057 0.78826556]]
№10
[ 69  68 149]
№11
[1.52993816 0.7310217 ]
№12
[[12 45]
 [18 60]]
№13
[[59 85]
 [61 99]]
№14
1343
№15
[[ 1  2  1  2]
 [-5  3  4  0]
 [-1  9 -4 -2]
 [ 0  4  1  1]]
№16
[[1.49096887]
 [1.1470114 ]
 [2.44765678]]
№17